In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/karan/Documents/MyDataProjects/Customer Behaviour/customer_shopping_behavior.csv') #reading the csv file

In [20]:
df.head() #displaying the first 5 rows of the dataframe

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [21]:
df.info() #displaying the information about the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [22]:
df.describe(include = 'all') #displaying the statistical summary of all categorical columns

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [23]:
df.isnull().sum() #checking for missing values in the dataframe

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [24]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median())) #filling missing values in 'Review Rating' column with the median of the respective category

In [25]:
df.isnull().sum() #checking for missing values in the dataframe after filling the missing values in 'Review Rating' column

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [26]:
df.columns = df.columns.str.lower().str.replace(' ', '_') #renaming the columns to lowercase and replacing spaces with underscores for better readability
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [27]:
df = df.rename(columns = {'purchase_amount_(usd)': 'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [28]:
#creating a new column (i.e. a new feature)
labels = ['Young adult', 'Adult', 'Mid-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4 , labels = labels) #creating a new column 'age_group' by categorizing the 'age' column into 4 quantiles and labeling them as 'Young adult', 'Adult', 'Mid-aged', and 'Senior'
df[['age', 'age_group']].head(10) #displaying the first 10 rows of the 'age' and 'age_group' columns to verify the new column creation

   age    age_group
0   55     Mid-aged
1   19  Young adult
2   50     Mid-aged
3   21  Young adult
4   45     Mid-aged
5   46     Mid-aged
6   63       Senior
7   27  Young adult
8   26  Young adult
9   57     Mid-aged

In [29]:
#create a new column to find purchase frequency in days
freq_mapping = {'Weekly': 7, 'Fortnightly': 14, 'Bi-Weekly': 14, 'Monthly': 30, 'Quarterly': 90, 'Every 3 Months': 90, 'Annually': 365} #mapping the purchase frequency to the number of days
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(freq_mapping) #creating a new column 'purchase_frequency_days' by mapping the 'frequency_of_purchases' column to the number of days using the freq_mapping dictionary
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10) #displaying the first 10 rows of the 'frequency_of_purchases' and 'purchase_frequency_days' columns to verify the new column creation

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [30]:
df[['discount_applied', 'promo_code_used']].head(10) #displaying the first 10 rows of the 'discount_applied' and 'promo_code_used' columns to check for any relationship between them

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [31]:
(df['discount_applied'] == df['promo_code_used']).all() #checking if the values in 'discount_applied' and 'promo_code_used' columns are the same for all rows

np.True_

In [32]:
df = df.drop('promo_code_used', axis = 1) #dropping the 'promo_code_used' column as it is redundant and has the same values as 'discount_applied' column
df.columns
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Mid-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Mid-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Mid-aged,365

In [33]:
%pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
from sqlalchemy import create_engine #importing the create_engine function from the SQLAlchemy library to create a connection to the PostgreSQL database

username = 'karan'
password = ''
host = 'localhost'
port = '5432'
database = 'customer_behaviour_db'

engine = create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}') #creating a connection to the PostgreSQL database using SQLAlchemy

table_name = 'customer_shopping_behavior' #specifying the table name to store the dataframe in the PostgreSQL database
df.to_sql(table_name, engine, if_exists='replace', index=False) #storing the dataframe in the PostgreSQL database, replacing the table if it already exists and not including the index

print(f"DataFrame has been successfully stored in the '{table_name}' table of the '{database}' database.") #printing a success message after storing the dataframe in the PostgreSQL database

DataFrame has been successfully stored in the 'customer_shopping_behavior' table of the 'customer_behaviour_db' database.

In [35]:
df.to_csv('/Users/karan/Documents/MyDataProjects/Customer Behaviour/customer_behaviour_cleaned.csv', index=False)
print("CSV saved to Documents/MyDataProjects/Customer Behaviour/customer_behaviour_cleaned.csv")

CSV saved to Documents/MyDataProjects/Customer Behaviour/customer_behaviour_cleaned.csv